---
output:
  html_document: default
  pdf_document: default
---
# Sub Question 2

However, the impact of the elite users may not be similar across all business categories. Yelp is mostly known for reviewing restaurants. As will be shown in the data exploration phase later, this category is used most often. Given this dominance, it is beneficial to investigate whether the influence of elite users on the average rating differs depending on the business type (restaurant vs. non-restaurant). This leads to our second sub question:

##### Does the relationship differ when analyzing only restaurants compared to non-restaurant businesses?

In order to determine whether the impact of user type on business ratings varies between restaurants and non-restaurant businesses, a two-way ANOVA will be applied. This method is widely used in applied statistics due to its simplicity and robustness in handling parametric tests (Luepsen, 2023). Given that two-way ANOVA effectively compares mean differences across categorical variables, it is ideal for analyzing how business category (restaurant vs. non-restaurant) moderates the relationship between Yelp user type (Elite vs. Non-Elite) and average business rating. Since the business category is a quasi-moderator, it may have both a direct effect on ratings and an interaction effect with user type. Two-way ANOVA allows us to test for these effects by examining whether Elite and Non-Elite users rate restaurants differently than non-restaurants. This method helps determine if the impact of reviewer status on ratings varies depending on the type of business being reviewed.


### Conceptual Model

#### Quasi-Moderators: Category of Business

We have categorized businesses into two groups: restaurants and non-restaurants. To assess whether the impact of Yelp user type (Elite vs. Non-Elite) on average business ratings vary by the category of the business, we will analyze their interaction. Specifically, we aim to determine whether elite and non-elite users tend to assign higher or lower ratings depending on whether a business is a restaurant or not. This quasi-moderator helps evaluate whether the business category influences the relationship between user type and average rating.


### Results

According to Table 2, the main effects of Elite Status and Business Category on user ratings are highly significant (p < 2×10^–16). This suggests that the average ratings are independently influenced by the type of business and the user's Elite status. Furthermore, the interaction between Elite Status and Business Category is also statistically significant (p = 7.65×10^–14), indicating that the effect of being an Elite user on ratings varies across various business categories. In conclusion, this implies that Elite users generally rate businesses differently from non-Elite users; however, the size of this difference varies for each category of business.


*(two-way anova table)*

The visual representation of these relationships is illustrated in Figure 2. The significant interaction discovered in the ANOVA is further illustrated by the fact that Elite users generally provide higher ratings (as evidenced by the boxes and medians shifting upward compared to Non-Elite users). However, the size of this difference is not consistent across Restaurants and Non-Restaurants. Most ratings for both categories are centered around 4 to 5 stars, but there are still outliers at extremely low ratings, which serves as evidence that both Elite and Non-Elite users can also leave negative reviews. In summary, this is in line with the statistical findings that Elite Status and Business Category both influence average ratings, and they do so in a way that is dependent on both factors simultaneously.

*(boxplot)*



